development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: async
  # adapter: redis
  # port: 6379
  # url: redis://clustercfg.atp2.0sxhbm.apne1.cache.amazonaws.com:6379
  # log_tags: [ActionCable]